title: CarbonROM Blog
email: support@carbonrom.org
description: >-
  Welcome to the CarbonROM Blog where you can find the latest news about what is
  happening at your favourite Android Custom ROM right now.
baseurl: ''
url: blog.carbonrom.org
twitter_username: CarbonROM
github_username: CarbonROM
markdown: kramdown
remote_theme: niklasbuschmann/contrast
lang: "en"

# Jekyll settings
paginate: 8                  # number of articles per page, remove to disable pagination
excerpt_separator: "\n\n\n"  # indicates the end of the excerpt by two blank lines
# Page settings
show_excerpts: true         # show article previews on the home page instead of headlines
hide_title: false            # remove site heading in the header
post_footer: true            # show previous and next links at the end of each post

date_format: "%B %d, %Y"     # see http://shopify.github.io/liquid/filters/date/
hide_title: false            # remove site heading in the header
post_footer: true            # show previous and next links at the end of each post
dark_theme: false            # use the dark mode as default
dark_header: true            # keep the header dark

navigation:                  # (optional) site navigation in the header
  - Get CarbonROM: https://get.carbonrom.org

icons:                       # (optional) icons in the header, see http://fontawesome.com/icons
  rss: "/feed.xml"
  telegram: "https://t.me/CarbonROM"
  discord: "https://discord.gg/3eZCPTx"
  envelope: "mailto:support@carbonrom.org"
  paypal: "https://www.paypal.com/cgi-bin/wapapp?cmd=_s-xclick&hosted_button_id=WQV8UFE9JR9TG"
